version: '3.9'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: manics
      MYSQL_ROOT_PASSWORD: password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: '-Xms1g -Xmx1g'
      discovery.type: single-node
      xpack.security.enabled: false
